---
# Defaults tasks for role ipsilon
- name: Installing required packages
  yum:
    name: "{{ ipsilon_packages }}"
    state: latest
  tags:
    - packages

# FAS Disabled
- name: Initializing ipsilon if needed
  command: >
    ipsilon-server-install
    --admin-user admin
    --secure yes
    --openid yes
    --saml2 yes
    --openidc yes
    --fas yes
    --ipa yes
    --info-sssd yes
    --form yes
    --hostname {{ ipsilon_httpd_hostname }}
  args:
    creates: /etc/ipsilon/idp/ipsilon.conf
  no_log: true
  register: ipsilon_install
  tags:
    - init

- name: Ipsilon admins template
  template:
    src: ipsilon-admins.sql.j2
    dest: /etc/ipsilon/idp/ipsilon-admins.sql
    owner: root
    group: root
    mode: '0644'
  register: ipsilon_admins
  tags:
    - init
    - admins

- name: Configure ipsilon admins
  shell: "set -o pipefail && sqlite3 /var/lib/ipsilon/idp/userprefs.sqlite < /etc/ipsilon/idp/ipsilon-admins.sql"
  changed_when: "1 != 1"

- name: Configuring httpd
  import_role:
    name: geerlingguy.apache
  when: apache_configure

- name: Branding ipsilon with logo
  copy:
    src: rocky_logo.png
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - /usr/share/ipsilon/ui/img/brand-lg.png
    - /usr/share/ipsilon/ui/img/brand.png

- name: Distributing openidc genkey script
  copy:
    src: genkey.py
    dest: /var/lib/ipsilon/idp/genkey.py
    mode: '0755'

# We'll get back to this soon
#  name: Ensuring backup user and jobs
#  include_role:
#    name: rocky-backup
#    tasks_from: client
#  vars:
#    - rocky_role: ipsilon
#    - role_backup_folders:
#        - /var/lib/ipsilon
#  tags:
#    - backup
